# Alias bash
- name: check if basic aliases is used
  stat:
    path: "{{docker_bash_alias_dir}}/.bash_aliases.d"
  register: is_basic_aliases_enabled
  when: docker_bash_alias_dir is defined

- name: Install Docker Aliases Files in {{docker_bash_alias_dir}}
  copy:
    content: |
      alias dcupd='docker-compose up -d'
      alias dcupdebug='docker-compose --profile debug up -d && docker-compose logs -f'
      alias dcdown='docker-compose down'
      alias dcdownv='docker-compose down -v'
      alias dc='docker-compose'
      alias dfh='df -h | grep -v /var/lib/docker/'
      alias dtest='docker run --name test --rm -it debian:11-slim /bin/bash'
    dest: "{{docker_bash_alias_dir}}/.bash_aliases.d/docker.aliases"
    mode: '0644'
  when: docker_bash_alias_dir is defined and is_basic_aliases_enabled.stat.exists