- name: Check if folder {{ docker_path }} exist
  stat:
    path: '{{ docker_path }}'
  register: docker_old_path
- name: Stop docker
  systemd:
    name: docker
    state: stopped
  when: not docker_old_path.stat.exists

- name: Move docker root dir
  command: mv /var/lib/docker {{ docker_path }}
  args:
    removes: '/var/lib/docker'
    creates: '{{ docker_path }}'
  notify: restart docker

- name: Create volumes symbolic link for docker users
  file:
    src: '{{ docker_path }}/volumes'
    dest: '{{ docker_volumes }}'
    state: link
