---
- name: Install requirements
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true
- name: Install GPG key
  apt_key:
    id: '{{ docker_apt_key.id }}'
    url: '{{ docker_apt_key.url }}'
    keyring: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
    state: present

- name: get release
  command: lsb_release -cs
  register: release
  changed_when: false
- name: Install apt sources list
  apt_repository:
    repo: '{{ docker_apt_repo }}'
    filename: docker
    state: present

- name: Install docker Engine
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: copy daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0664'
  notify: restart docker

- name: check natif kernel # avoid WSL
  shell: uname -r | grep microsoft
  register: kernel
  changed_when: false
  failed_when: false

- name: fix iptables to use services on WSL
  shell:
    cmd: |
      update-alternatives --set iptables /usr/sbin/iptables-legacy
      update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
  when: kernel.rc is defined and not kernel.rc and ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "24" # only for WSL
