---
# tasks file for docker
- include_tasks: dns-from-host.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '22' and docker_get_host_dns and docker_netplan_file is defined
- include_tasks: install-docker.yml
  tags: install
- include_tasks: install-docker-compose.yml
  when: docker_compose_install
  tags: install
- include_tasks: users.yml
  tags: install
- include_tasks: alias-docker-compose.yml
  tags: configure
- include_tasks: pip-docker.yml
  tags: configure
- include_tasks: networks.yml
  tags: configure
- include_tasks: change-dir.yml
  tags: configure
  when: docker_path != '/var/lib/docker'
- include_tasks: config-registries.yml
  tags: configure
  when: docker_registries is defined and docker_registries | length > 0
- include_tasks: common-registries.yml
  tags: configure
  when: docker_shared_registries and docker_registries is defined and docker_registries | length > 0
