---
# tasks file for docker
- import_tasks: install-docker.yml
  become: true
  tags: install
- import_tasks: install-docker-compose.yml
  become: true
  when: docker_compose_install
  tags: install
- import_tasks: users.yml
  become: true
  tags: install
- import_tasks: alias-docker-compose.yml
  tags: configure
- import_tasks: pip-docker.yml
  become: true
  tags: configure
- import_tasks: networks.yml
  become: true
  tags: configure
- import_tasks: change-dir.yml
  become: true
  tags: configure
  when: docker_path != '/var/lib/docker' or docker_volumes is defined