- name: Add external network(s)
  community.docker.docker_network:
    name: "{{item.name}}"
    state: present
    ipam_config:
      - subnet: "{{item.subnet}}"
        gateway: "{{item.gateway}}"
  loop: "{{docker_networks}}"
  when: docker_networks is defined